### ISSUE TITLE
Change the logo write up to "shipp it " and you can suggest some logo for Shipp It .

### ISSUE THREAD

**Issue by 7saikat7** [7saikat7/supply_chain#33]

**Comment by Anosh21** [comment]
I would like to work on this issue under JWOC.

**Comment by VaishnaviNigam25** [comment]
@7saikat7  I would like to work on this sunder JWOC, please assign it to me

**Comment by VaishnaviNigam25** [comment]
Can you please elaborate on what exactly has to be done, since when I cloned this I see something like this, and I'm not sure if this is the final project's layout... plz elaborate @7saikat7 
![image](https://user-images.githubusercontent.com/71756799/154032627-97c6516c-9198-40d2-bbc2-3f6cb736a0d0.png)

**Comment by 7saikat7** [comment]
The logo added on the readme file .. please take it into consideration , it's mostly u have to build a logo not coding work as of now

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC


If the current logo is not taken into consideration, i would like to work on this issue.
